name: 'test'

on: [push]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn

      - uses: ./
        with:
          ovpnConfig: ${{ secrets.OVPN_CONFIG }}
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
